application.environmentId=p

# Used to create application-context specific dirs such as for data
# OR file name prefixes such as <application.dirOrFileName>-someFile.log
#application.dirOrFileName=@project.artifactId@

application.hydraConfig.adminUrl=${HYDRA_ADMIN_URL}

application.loggingConfig.level=INFO
application.loggingConfig.rootDir=/lfs/envp/logs/tomcat/spring-boot-apps/${spring.application.name}
