# All properties whose value may be needed by the application at runtime should be nested under 'application.' and
# the corresponding spring property should be bound to it (eg: server.port is bound to application.serverHttpPort).
#
# The above rule implicitly enforces the following two rules:
# 1. An environment specific property file should NEVER have a property that does not start with "application."
# 2. All spring properties not bound to an 'application.' property are essentially be considered read-only.
#    If any of those read-only properties need to be used at runtime by the application then they
#    should be loaded into ApplicationRuntimeInfo (here Info highlights that the properties are read only).

# Also note that some 'application.' properties defined here have no value. This is intentional because it makes it
# easier to do line-by-line comparison of this property file with an env specific property file which makes it easier
# to maintain the property files and reduces changes of bugs.

application.environmentId=

application.serverHttpPort=8082

# Used to create application-context specific dirs such as for data
# OR file name prefixes such as <application.dirOrFileName>-someFile.log
application.dirOrFileName=@project.artifactId@

# If this is changed, then uncomment the server.servlet.context-path and set it.
application.servletContextPath=/

application.sessionTimeoutInSeconds=3600

application.actuatorPort=${application.serverHttpPort}
application.microMeterConfig.enableJmxMetrics=true

application.hydraConfig.adminUrl=

# Change this to control log level of net.fbdms.idm.consentapp classes. For all others, use logging.level.*
application.loggingConfig.level=INFO

application.loggingConfig.rootDir=
application.loggingConfig.mainLogFileName=application
application.loggingConfig.mainLogFilePath=${application.loggingConfig.rootDir}/${application.loggingConfig.mainLogFileName}.log
application.loggingConfig.stacktraceLogFileName=${application.loggingConfig.mainLogFileName}.stacktrace
application.loggingConfig.stacktraceLogFilePath=${application.loggingConfig.rootDir}/${application.loggingConfig.stacktraceLogFileName}.log

#server.servlet.context-path=${application.servletContextPath}

server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,application/javascript,application/json

#spring.main.log-startup-info=false
# Whether the banner should be printed on System.out (console), sent to the configured logger (log), or not produced at all (off).
#spring.main.banner-mode=log



###############################################################################
### Logging properties:
###############################################################################

# Note:
# To ensure logging occurs in correct log files, please always specify the -Dspring.profiles.active=<profile>
# as a JVM arg eg: -Dspring.profiles.active=winLocal
# In Java 17 and above, it can ALSO be specified as a program argument instead of a VM arg.
# For example: --spring.profiles.active=<profile>

logging.charset.console=UTF-8
logging.charset.file=UTF-8
logging.level.net.fbdms.idm.consentapp=${application.loggingConfig.level}

# Defaults is defined in logback.xml and is INFO.
logging.level.root=WARN

logging.level.org.springframework=ERROR
logging.level.org.springframework.web=ERROR
logging.level.ch.qos.logback=WARN

# Headers + protocol info. Valid values are: OFF, ERROR, WARN, INFO, DEBUG, TRACE
logging.level.org.apache.hc.client5.http=ERROR

# Raw bytes OFF
logging.level.org.apache.hc.client5.http.wire=OFF



###############################################################################
### Spring Actuator properties:
###############################################################################

management.server.port=${application.actuatorPort}
management.endpoint.logfile.external-file=${application.loggingConfig.mainLogFilePath}

# Disable all Actuator endpoints unless explicitly enabled (like management.endpoint.env.enabled=true)
management.endpoints.enabled-by-default=false

# Explicitly enable/disable specific endpoints:
management.endpoint.configprops.enabled=true
management.endpoint.env.enabled=true
#management.endpoint.env.show-values=when-authorized
management.endpoint.env.show-values=always
management.endpoint.health.enabled=true
management.endpoint.health.show-details=when-authorized
management.endpoint.info.enabled=true
management.endpoint.logfile.enabled=true
management.endpoint.loggers.enabled=true
management.endpoint.metrics.enabled=true
management.endpoint.shutdown.enabled=false
management.endpoint.refresh.enabled=true

# Expose enabled endpoints over HTTP:
management.endpoints.web.exposure.include=auditevents,configprops,env,health,info,loggers,metrics,refresh

# Not expose enabled endpoints over HTTP:
#management.endpoints.web.exposure.exclude=



###############################################################################
### Spring MicroMeter properties:
###############################################################################

spring.jmx.enabled=${application.microMeterConfig.enableJmxMetrics}

management.metrics.enable.jvm=true
#management.metrics.enable.jvm.memory=true
#management.metrics.enable.jvm.gc=true
#management.metrics.enable.jvm.threads=true
#management.metrics.enable.jvm.classes=true
#management.metrics.enable.jvm.uptime=true

management.metrics.enable.system=true
#management.metrics.enable.system.cpu=true
#management.metrics.enable.system.filesystem=true
#management.metrics.enable.system.process=true
#management.metrics.enable.system.network=true

management.metrics.enable.http=true
management.metrics.enable.http.server.requests=true
management.metrics.enable.http.client.requests=true

management.metrics.enable.cache=true
management.metrics.enable.timer=true
#management.metrics.enable.spring.integration=true

# Enable Custom Metrics (enabled by default. Used to register your own metrics like counter, gauge, or timer.
# To do that you would create it, register with micro meter registry, change it as needed, and then monitor.
management.metrics.enable.custom.metrics=true

# Enable Actuator Health Metrics
management.metrics.enable.health=true

# Enable Logging Metrics
management.metrics.enable.logging=true

# Enable Thread Pool Metrics
management.metrics.enable.threadpool=true

# Enable Spring Boot Auto-Configuration Metrics
#management.metrics.enable.spring.boot.autoconfiguration=true



###############################################################################
### Miscellaneous Spring properties:
###############################################################################
spring.devtools.livereload.enabled=false
spring.devtools.restart.enabled=false

#######################################################################
### Following should either never be changed or never changed directly:
#######################################################################

# Configure Spring so that it lets our ControllerAdvice handle 'NoHandlerFoundException' rather than handling
# it directly by redirecting it to Spring's DefaultHandlerExceptionResolver.
# See https://reflectoring.io/spring-boot-exception-handling/
# spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# This will prevent one particular execution-flow that responds with html (which we never want) rather than JSON.
# It will occur when an AccessDeniedException is thrown anywhere and the authentication token in the
# security context represents an actual authenticated user AND NOT the 'anonymous' user (as defined by Spring).
# One case this can happen, for example, is when the CSRF token in the request was either incorrect or non-existent.
# In this case, line 174 of ExceptionTranslationFilter will be invoked which will return the response as HTML if
# an error page is configured in the AccessDeniedHandler.
# Disabling this would enable Spring to send a JSON response instead.
server.error.whitelabel.enabled=false

spring.application.name=@project.name@
spring.profiles.default=winLocal

spring.profiles.group.winLocal[0]=win
spring.profiles.group.winLocal[1]=local
#spring.profiles.group.winLocal[2]=someMockService

spring.profiles.group.linuxLocal[0]=linux
spring.profiles.group.linuxLocal[1]=local

server.port=${application.serverHttpPort}

# This will be used when a normal 'kill' signal is sent by the OS.
# such as when killing the application process via 'kill' without -9
server.shutdown=graceful
server.shutdown.grace-period=60s

server.session-timeout=${application.sessionTimeoutInSeconds}
# See resource-locations in StaticResourceConfig
#spring.web.resources.static-locations=classpath:/public/,classpath:/static/client/,file:/path/to/your/static/files
