application.environmentId=winLocal

application.serverHttpPort=8082

# Used to create application-context specific dirs such as for data
# OR file name prefixes such as <application.dirOrFileName>-someFile.log
#application.dirOrFileName=@project.artifactId@

application.hydraConfig.adminUrl=http://localhost:4445

application.loggingConfig.level=DEBUG
application.loggingConfig.rootDir=target-consent-app/logs

# HTTP client debug logging useful when tracing Hydra admin API calls locally
logging.level.org.apache.hc.client5.http=DEBUG
