application.environmentId=linuxLocal

# Used to create application-context specific dirs such as for data
# OR file name prefixes such as <application.dirOrFileName>-someFile.log
#application.dirOrFileName=@project.artifactId@

application.hydraConfig.adminUrl=http://localhost:4445

application.loggingConfig.level=DEBUG
application.loggingConfig.rootDir=target/logs
